import React from 'react'
import clcs from "../clcs.png";
import autiron from "../autiron.png";

function Exp5B(props) {
  return (
    <div>
      <h2 className={`text-${props.mode==="dark"?"light":"dark"}`}>Experiment-5B</h2>
      <h3 className={`text-${props.mode==="dark"?"light":"dark"}`}>Close Loop Control System(CLCS) analysis using simulation sotware</h3>
    <div className='container my-4'/>
    <div class="row">
    <div class="col-2">
      <nav id="navbar-example3" class="h-100 flex-column align-items-stretch pe-4 border-end">
        <nav class="nav nav-pills flex-column">
          <a className={`nav-link text-${props.mode==="light"?"dark":"light"}`} href="#item-1">Closed Loop Control System</a>
          <nav class="nav nav-pills flex-column">
            <a className={`nav-link ms-3 my-1 text-${props.mode==="light"?"dark":"light"}`} href="#item-1-1">Advantages</a>
            <a className={`nav-link ms-3 my-1 text-${props.mode==="light"?"dark":"light"}`} href="#item-1-2">Disadvantages</a>
          </nav>
          <a className={`nav-link text-${props.mode==="light"?"dark":"light"}`} href="#item-3">Applications</a>
        </nav>
      </nav> 
    </div>

    <div class="col-8">
      <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true" class="scrollspy-example-2" tabindex="0">
        <div id="item-1">
          <h4 className={`text-${props.mode==="dark"?"light":"dark"}`}><strong>Closed Loop Control System</strong></h4>
          <p className={`text-${props.mode==="dark"?"light":"dark"}`}>A closed-loop control system is a type of control system in which the controlling action shows dependency on the generated output of the system. In simple words, in these systems, the output of the system controls the input applied to the system.</p>
            <img src={clcs} width={`850px`} alt={`...`}/>
            <figcaption className={`text-${props.mode==="dark"?"light":"dark"}`} align={`center`}>Closed Loop control system</figcaption>
            <div className={`my-3`}/>
          <p className={`text-${props.mode==="dark"?"light":"dark"}`}>The variation in input according to the output leads to produce more accurate system output. Thus controllability in the closed-loop system is achieved through the output generated by utilizing a feedback path.</p>
          <p className={`text-${props.mode==="dark"?"light":"dark"}`}>Closed-loop systems are considered as fully automatic control system because it is designed in a way that the achieved output is automatically compared with the reference input to have the required output.</p>
          <p className={`text-${props.mode==="dark"?"light":"dark"}`}>Examples: Automatic Electric Iron, Temperature Control System, </p>
            <img src={autiron} width={`850px`} alt={`...`}/>
            <figcaption className={`text-${props.mode==="dark"?"light":"dark"}`} align={`center`}>Control system for automatic iron</figcaption>
        </div>

          <div className={`my-5`}/>
      <div id="item-1-1">  
          <h5 className={`text-${props.mode==="dark"?"light":"dark"}`}><strong>Advantages of Closed Loop Control System</strong></h5>
          <li className={`text-${props.mode==="dark"?"light":"dark"}`}>The closed-loop system is more accurate than the open-loop system because of controlling through the output signal.</li>
                   <li className={`text-${props.mode==="dark"?"light":"dark"}`}>These types of systems are less affected by noise and other environmental disturbances.</li>
                   <li className={`text-${props.mode==="dark"?"light":"dark"}`}>It provides a high-frequency range of operation.</li>
                   <li className={`text-${props.mode==="dark"?"light":"dark"}`}>These are more flexible as compared to the open-loop system.</li>
              </div>
          <div className={`my-4`}/>
            <div id="item-1-2">
                <h5 className={`text-${props.mode==="dark"?"light":"dark"}`}><strong>Disadvantages of Closed Loop Control System</strong></h5> 
                   <li className={`text-${props.mode==="dark"?"light":"dark"}`}>The addition of the feedback elements leads to the generation of complex structures.</li>
                   <li className={`text-${props.mode==="dark"?"light":"dark"}`}>Closed-loop systems are not economical.</li>
                   <li className={`text-${props.mode==="dark"?"light":"dark"}`}>The problem of instability in output is a crucial factor of the closed-loop system as the presence of feedback causes timely variation in the system’s output.</li>
              </div>
          <div className={`my-4`}/>
            <div id="item-1-3">
                <h5 className={`text-${props.mode==="dark"?"light":"dark"}`}><strong>Applications of Closed Loop Control System</strong></h5>
                <p className={`text-${props.mode==="dark"?"light":"dark"}`}>In our day to day life, we come across various uses of closed-loop systems. From an air conditioner that manages to provide the desired value of room temperature by making required adjustments to automatic washing machines that provide the required level of dryness to the cloth after washing.</p>
                <p className={`text-${props.mode==="dark"?"light":"dark"}`}>In a similar way from an automatic toaster, water level controller, home heating system to dc motor speed control and missile launching system, etc. everything that is designed to generate the required output with accuracy is the closed-loop system.</p>
                </div>
      </div>
    </div>
  </div>
</div>


  )
}

export default Exp5B
